# Generated by Django 4.0 on 2022-02-12 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_imagemodel_file_alter_videomodel_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['-file']},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'ordering': ['-file']},
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videomodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
