# Generated by Django 4.0 on 2022-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_imagemodel_options_alter_videomodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='file',
            field=models.ImageField(upload_to='image/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='file',
            field=models.FileField(upload_to='video/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time'),
        ),
    ]
