# Generated by Django 4.0 on 2022-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_imagemodel_file_alter_imagemodel_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='file',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='file',
            field=models.FileField(upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
